version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run:
        name: test
        command: python test
      - persist_to_workspace:
        root: .
        paths:
          - .

  docker_build_push:
    working_directory: /app
    docker:
      - image: docker:18.05.0-ce-dind
    steps:
      - attach_workspace:
        at: .
      - setup_remote_docker:
        version: 18.05.0-ce
      - run:
        name: docker image build
        command: docker image build -t joondocker/echo-python:latest .
      - run:
        name : docker image ls
        command: docker image ls
      - run:
        name: docker login
        command: docker login -u $DOCKER_USER -P $DOCKER_PASS
      - run:
        name: release latest
        command: docker image push joondocker/echo-python:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - docker_build_push:
        requires:
          - build
        filters:
          branches:
            only: master
